exclude:
  - 'node_modules/*'
  - 'bower_components/*'

linters:
  EmptyLineBetweenBlocks:
    enabled: false
  Indentation:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  Comment:
    enabled: false
  LeadingZero:
    enabled: false
