#!/bin/bash
unset IFS
set -eufo pipefail

audit() {
    govulncheck
}

bashate() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 .venv/bin/bashate -i E006
}

govulncheck() {
    command govulncheck -scan package ./...
}

kirill() {
    command kirill .
}

lint() {
    bashate
    kirill
    shellcheck
    shfmt
    slick
}

shellcheck() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 shellcheck
}

shfmt() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 shfmt -w -i 4
}

slick() {
    stank -print0 -sh . |
        xargs -0 -n 1 slick
}

TASKS=' \
    audit \
    bashate \
    govulncheck \
    kirill \
    lint \
    shellcheck \
    shfmt \
    slick'

SELECTED_TASKS='lint'

if [ "$#" -gt 0 ]; then
    SELECTED_TASKS="$*"
fi

for TASK in $SELECTED_TASKS; do
    case "$TASKS" in
    *"$TASK"*)
        "$TASK"
        ;;
    *)
        echo "error: no such task: $TASK"
        exit 1
        ;;
    esac
done
