(source melpa)
(source marmalade)

(depends-on "markdown-mode")

(depends-on "monokai-theme")

(depends-on "window-jump")
(depends-on "dired+")
(depends-on "dired-single")
(depends-on "dired-details")

(depends-on "fiplr")
(depends-on "tabbar")
(depends-on "tabbar-ruler")
(depends-on "fold-dwim")
(depends-on "hideshowvis")
(depends-on "undo-tree")
(depends-on "ack-and-a-half")

(depends-on "gitignore-mode")
(depends-on "json-mode")
(depends-on "yaml-mode")
(depends-on "haskell-mode")
(depends-on "mmm-mode")
(depends-on "vimrc-mode")
(depends-on "rust-mode")
(depends-on "go-mode")
(depends-on "ntcmd")
(depends-on "ess")
(depends-on "fuel")
(depends-on "erlang")
(depends-on "clojure-mode")
(depends-on "scala-mode2")
(depends-on "coffee-mode")
(depends-on "d-mode")
(depends-on "dart-mode")
(depends-on "fasm-mode")
(depends-on "fsharp-mode")
(depends-on "io-mode")
(depends-on "j-mode")
(depends-on "less-css-mode")
(depends-on "lua-mode")
(depends-on "wolfram-mode")
(depends-on "matlab-mode")
(depends-on "newlisp-mode")
(depends-on "tuareg") ; ocaml
(depends-on "oz")
(depends-on "racket-mode")
(depends-on "sass-mode")
(depends-on "stylus-mode")
(depends-on "brainfuck-mode")