#!/bin/sh
unset IFS
set -eu

BREAK_CHARS="\"#'(),;\`\\|!?[]{}" rlwrap \
    -b $BREAK_CHARS \
    --remember \
    -c \
    -f ~/.ccl_completions \
    -H ~/.ccl_history \
    -s 1000000 \
    lx86cl \
    ${1+"$@"}
