#!/bin/sh
# For your shebangs
#
# mkdir -p ~/bin
# cp .../shmatlab% ~/bin/shmatlab%
#
unset IFS
set -euf

code="$(cat <<END
varargin = regexp('${1+"$@"}', ' ', 'split');
nvarargin = length(varargin);
run('$1');
exit
END
)"

matlab \
    -nojvm \
    -nodisplay \
    -nosplash \
    -r "$code" |
    tail -n +16
