#!/usr/bin/tclsh
# mcandre's preferred vera++ ruleset.
#
# Install:
#
# cp -r /usr/local/lib/vera++ ~/.vera++
# mv ~/.vera++/profiles/default ~/.vera++/profiles/default.bak
# ln -s vera ~/.vera++/profiles/default
#

set rules {
    F001

    L001
    L002
    L003
    L004
    L005
    L006

    T001
    T002
    T004
    T005
    T006
    T007
    T008
    T009
    T010
    T013
    T015
    T016
    T017
    T018
    T019
}
