#!/bin/bash
unset IFS
set -eufo pipefail

#
# Sync changes between local and remote for current git branch
#

usage() {
    printf "Usage: $0 [OPTIONS]\n\n"
    printf -- "-n\tEnable nonce\n"
    printf -- "-d\tEnable debug mode\n"
    printf -- "-h\tShow usage menu\n"
}

DEBUG=0
NONCE=0

while [ "$#" -gt 0 ]; do
    ARG="$1"

    case "$ARG" in
        '-h')
            usage
            exit
            ;;
        '-d')
            DEBUG=1
            shift
            ;;
        '-n')
            NONCE=1
            shift
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [ "$DEBUG" -eq 1 ]; then
    set -x
else
    tty -s
    exec &>/dev/null 2>&1
fi

git fetch --all

if [ "$NONCE" -eq 1 ]; then
    date >.kick
fi

git add .

if [ -n "$(git status --porcelain)" ]; then
    git commit -m 'up'
    git pull
    git push
fi

git fetch --tags
git push --tags
