#!/usr/bin/env bash
#
# post-merge-checkout
#
# Clean and update on git pull, merge, and checkout.
#
# Install:
#
# ln -s .../post-merge-checkout .../.git/hooks/post-merge
# ln -s .../post-merge-checkout .../.git/hooks/post-checkout

#
# file_run $1
#
# Return true if files matching pattern $1 have changed in git.
# Otherwise, return false.
#
# Example: file_run package.json && npm install
#
file_run() {
  git diff HEAD@{1} HEAD --name-only | grep --quiet "$1"
}

#
# branch_run $1
#
# Returns true if current branch matches pattern $1 in git.
# Otherwise, returns false.
#
# Example: branch_run master && echo "Remember, you're on master!"
#
branch_run() {
  [[ $(git rev-parse --symbolic-full-name HEAD) = */"$1" ]]
}

file_run Cask && \
  bash -c 'cd ~/.emacs.d/ && cask install'

file_run .emacs && \
  emacs --batch --eval '(load "~/.emacs")' -f batch-byte-compile ~/.emacs

file_run .vimrc && \
  vim +BundleUpdate +BundleInstall +qall
